coverage:
  status:
    project:
      default:
        target: << config(coverage.project.target)|default(["80%"])|scalar >>
        threshold: << config(coverage.project.threshold)|default(["2%"])|scalar >>

    patch:
      default:
        target: << config(coverage.patch.target)|default(["80%"])|scalar >>
        threshold: << config(coverage.patch.threshold)|default(["5%"])|scalar >>

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
