coverage:
  status:
    project:
      default:
        target: {{CODECOV_PROJECT_TARGET | default('80%')}}
        threshold: {{CODECOV_PROJECT_THRESHOLD | default('2%')}}

    patch:
      default:
        target: {{CODECOV_PATCH_TARGET | default('80%')}}
        threshold: {{CODECOV_PATCH_THRESHOLD | default('5%')}}

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
