override:
  phpmetrics.coupling.max_afferent: 17
  phpmetrics.coupling.max_efferent: 25
  php.versions: ["8.3", "8.4", "8.5"]
  ci.pr.max_lines_changed: 2000
  ci.piqule_bin: bin/piqule
  sonar.organization: haspadar-org
  sonar.projectKey: haspadar_piqule
  infection.min_msi: 80
  infection.min_covered_msi: 90
  psalm.project.files:
    - "../../bin/piqule"
    - "../../bin/piqule-check"
    - "../../bin/piqule-fix"
    - "../../bin/piqule-sync"
    - "../../bin/piqule-tokens-check"

append:
  exclude:
    - templates
