coverage:
  precision: 2
  round: down
  range: "68...100"

  status:
    project:
      default:
        metric: paths
        target: 70%
        threshold: 2%

    patch:
      default:
        metric: paths
        target: 75%
        threshold: 5%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
