# Hadolint configuration (Piqule managed)

failure-threshold: << config(hadolint.failure_threshold)|default(["error"])|scalar >>

ignored: << config(hadolint.ignored_yaml)|default(["[]"])|scalar >>

override:
  error: << config(hadolint.override.error_yaml)|default(["[]"])|scalar >>
  warning: << config(hadolint.override.warning_yaml)|default(["[]"])|scalar >>
