coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        coverage_type: branch

    patch:
      default:
        target: 80%
        threshold: 5%
        coverage_type: branch

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
