extends: default

ignore: |
<< config(yamllint.ignore)|default(["vendor/**","node_modules/**","build/**","var/**",".piqule/**/html/**",".piqule/**/coverage-report/**"])|format("  %s")|join("\n") >>

rules:
  document-start: disable

  # truthy is disabled intentionally to avoid false-positives
  # in GitHub Actions and CI-related YAML files
  truthy: disable

  # line-length is limited to 120 characters; longer limits are common
  # in CI workflows where commands cannot be easily split across lines
  line-length:
    max: << config(yamllint.line_length.max)|default(["120"])|join("") >>
    level: warning
