sonar.sources=<< config(sonar.sources)|join(",") >>
sonar.tests=<< config(sonar.tests)|join(",") >>
sonar.cpd.exclusions=<< config(sonar.cpd.exclusions)|join(",") >>
sonar.coverage.exclusions=<< config(sonar.coverage.exclusions)|join(",") >>
