sonar.sources=<< config(sonar.sources)|join(",") >>
sonar.tests=<< config(sonar.tests)|join(",") >>
sonar.exclusions=<< config(sonar.exclusions)|join(",") >>
sonar.php.coverage.reportPaths=<< config(sonar.coverage.reportPath)|join(",") >>
